### ISSUE TITLE
Lefthook not running hooks when called from sub-directory

### ISSUE THREAD

**Issue by jamiek-acl** [evilmartians/lefthook#215] opened 2021-06-29 16:33 UTC
My lefthook.yml is in the root, so when I run `lefthook run pre-commit` from the root, all the hooks run:

```
~/$ lefthook run pre-commit
Lefthook v0.7.6
RUNNING HOOKS GROUP: pre-commit
prettier (SKIP. NO FILES FOR INSPECTION)
eslint (SKIP. NO FILES FOR INSPECTION)
```

But when I run it from a subfolder, it seems to not be finding the config file so it is not linting my files when I do a commit:
```
~/client/apps/xxx$ lefthook run pre-commit
Lefthook v0.7.6
RUNNING HOOKS GROUP: pre-commit
SUMMARY: (SKIP EMPTY)

~/client/apps/xxx$ lefthook run asdfghjk1234
Lefthook v0.7.6
RUNNING HOOKS GROUP: asdfghjk1234
SUMMARY: (SKIP EMPTY)
```

How does lefthook look for the config file? I dont want to have to create aliases all over the place. My directory structure is like this:

```
.git/
  hooks/
    commit-msg
    prepare-commit-msg
    pre-commit
.lefthook/
  commit-msg/
    story_number
lefthook.yml
client/
  apps/           # many react apps under here
```

My lefthook.yml looks like this:
```
commit-msg:
  scripts:
    "story_number":
      runner: sh
pre-commit:
  parallel: true
  commands:
    eslint:
      root: "client/"
      glob: "client/apps/**/*.js"
      run: yarn lint {staged_files}
    prettier:
      root: "client/"
      glob: "client/apps/**/*.js"
      run: yarn prettier --check {staged_files}
```

Thanks.

**Comment by spearmootz** [comment] 2021-09-02 16:57
i also have a problem where node_modules is not in my root git but rather in the src folder so this fails as well

**Comment by jamiek-acl** [comment] 2021-09-02 17:03
Update: this is working now but sadly I don't recall what I did to make it work, sorry.

**Comment by spearmootz** [comment] 2021-09-02 17:53
@jamiek-acl  did you happen to install lefthook globally?

**Comment by jamiek-acl** [comment] 2021-09-02 18:00
Yes

```
~/$ which lefthook -a
/Users/jamie/.rbenv/shims/lefthook

~/$ echo $PATH
/usr/local/opt/v8@3.15/bin:
/Users/jamie/.rbenv/shims/lefthook:
/Users/jamie/.rbenv/shims:
/usr/local/opt/v8@3.15/bin:
/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin:
/Users/jamie/.avn/bin:
/Users/jamie/.nvm/versions/node/v10.15.1/bin:
/Users/jamie/.rbenv/shims:
/usr/local/bin:
/usr/bin:
/bin:
/usr/sbin:
/sbin:
/.npm-global/bin:
/Users/jamie/.rbenv/shims
```

**Comment by mrexox** [comment] 2024-12-21 08:03
This must be fixed in latest versions of lefthook since it moved to absolute paths for Git. Please, reopen if you can reproduce, or create a new issue!

**Closed by mrexox** 2024-12-21 08:03 UTC
Labels: bug
