### ISSUE TITLE
Installation fails inside a repo using submodules

### ISSUE THREAD

**Issue by zimmicz** [evilmartians/lefthook#332] opened 2022-09-26 14:36 UTC
I've found a few PRs mentioning the support for Git submodules had been already delivered. However, I keep getting an error when running `npm i -D lefthook` inside a git submodule. You can easily reproduce the behaviour using these steps:

```
mkdir test && cd test
git init
git submodule add git@github.com:SavantBuffer/DbConnector.git
cd DbConnector
npm i -D lefthook
```

The error I get after installation:

```
SYNCING
Error: open /home/zimmi/dev/git-submodules-playground/.git/modules/DbConnector/info/lefthook.checksum: no such file or directory
```

I'm running version `1.1.1` on Ubuntu Focal.

**Comment by mrexox** [comment] 2022-09-28 09:27
Hey! Thank you for the issue! I guess lefthook has never been tested to work with git submodules, but it makes sense. I want to fix this bug in next release. Unfortunately I don't have enough resources to accomplish this task quickly. I shall get to it in 2-3 weeks.

**Comment by zimmicz** [comment] 2022-09-28 11:29
Would it be hard to help you? I have no knowledge of golang though and I am not even sure about the way to tackle this.

**Comment by mrexox** [comment] 2022-09-30 10:11
I guess the problem is somewhere in `internal/git/`, and we should respect submodules there. If you have a will, you can try debugging it yourself! If you find something, please, open the PR, and I can jump in!

**Comment by mrexox** [comment] 2022-11-04 15:39
Hm, I am not getting this error. Could you check v1.1.4? Maybe it was already fixed?

**Comment by mrexox** [comment] 2022-11-05 09:37
I guess the problem was that lefthook didn't run `install` in postscripts in 1.1.1 version. This should be already fixed in further versions, so I am closing this issue.

Please, tell if you have other problems, or this bug reproduces someway!

**Closed by mrexox** 2022-11-05 09:37 UTC
Labels: bug

**Comment by zimmicz** [comment] 2022-11-07 13:02
:clap: works like charm!
