### ISSUE TITLE
Hooks not working after migrate from husky

### ISSUE THREAD

**Issue by eavam** [evilmartians/lefthook#159] opened 2020-11-26 21:27 UTC
I catch a bug when migrating from husky. Husky changed `hooksPath` in my git config.
In file `.git / config` has next string:
```
[core]
hooksPath = .husky
...
```
So after migrating to lefthook, it doesn't work. I think it is want to add reset `hooksPath` after `lefthook install` or documentation about removing `hooksPath` for migrating from husky.
I am testing on husky v5.

**Comment by ryands17** [comment] 2021-02-15 10:52
Facing the same issue here.

**Comment by stevelacy** [comment] 2021-04-22 16:53
I ran `npx husky uninstall` to remove the `hooksPath` from `.git/config`

**Comment by DmitryTsepelev** [comment] 2021-04-26 11:09
Looks like a duplicate of #149, and the solution is to clear `hooksPath` as Steve suggested.

**Closed by DmitryTsepelev** 2021-04-26 11:09 UTC

**Comment by Envek** [comment] 2021-04-26 14:25
Or should we add support for custom `hooksPath`? See https://github.com/evilmartians/lefthook/issues/170

**Comment by brentmitchell25** [comment] 2021-07-22 21:52
I also wanted to add to this that while my global hooks path was not set, husky had overwritten the local `hooksPath` in my `.git/config` directory. I removed the line and everything works as expected.
